language: python

python:
  - "2.7"
  - "3.5"

sudo: "required"

addons:
    firefox: "latest"

env:
  matrix:
  - TOXENV=foxpuppet GUI=1

before_install:
  - if [ $TOXENV ]; then sudo pip install tox; fi
  - if [[ $TOXENV == 'foxpuppet' ]]; then wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz; fi
  - if [[ $TOXENV == 'foxpuppet' ]]; then gunzip -c geckodriver.tar.gz | tar xopf -; fi
  - if [[ $TOXENV == 'foxpuppet' ]]; then chmod +x geckodriver && sudo mv geckodriver /usr/local/bin; fi

notifications:
  webhooks:
    urls:
      - "https://silne30-foxpuppet.getbadges.io/api/app/webhook/b71ddba7-6feb-412c-8728-3efef552d02b"
    on_start: "change"

before_script:
  - "flake8 ."
  - if [ $GUI ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi

script:
  - "py.test --capture=sys --showlocals --tb=long --driver Firefox foxpuppet/tests"