language: python

python:
  - "2.7"
  - "3.5"

sudo: "required"

env:
  global:
    - DISPLAY=:99.0
  matrix:
    - PYTHON_2=2.7.11
    - PYTHON_3=3.5.1

before_install:
  - pip install mozdownload mozinstall
  - mozdownload --type daily --branch mozilla-central --destination firefox.tar.bz2
  - mozinstall firefox.tar.bz2
  - sudo ln -sf $PWD/firefox/firefox /usr/local/bin/firefox
  - pip install tox
  - wget -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz; fi
  - gunzip -c geckodriver.tar.gz | tar xopf -; fi
  - chmod +x geckodriver && sudo mv geckodriver /usr/local/bin; fi

notifications:
  webhooks:
    urls:
      - "https://silne30-foxpuppet.getbadges.io/api/app/webhook/b71ddba7-6feb-412c-8728-3efef552d02b"
    on_start: "change"

before_script:
  - /etc/init.d/xvfb start

script:
  - tox